Adding support for list type properties filters
neo4j-graphql/neo4j-graphql-java pull request #285
Opened 2023-01-11 09:29 UTC by AakashSorathiya

This PR adds support for filters which can be used with list type properties of Node or Relation.
Filters added are: `INCLUDES_ANY`, `INCLUDES_ALL`, `NOT_INCLUDES`.

This PR is in reference with the PR of cypher-dsl library (https://github.com/neo4j-contrib/cypher-dsl/pull/374) which includes enhancement for list filters in that library. 

Test cases are included for all the code changes implemented.

2023-01-16 12:08 UTC, Andy2003 requested changes
Also update the schema-tests, they are currently failing.

2023-01-19 17:38 UTC, AakashSorathiya commented on core/src/main/kotlin/org/neo4j/graphql/Predicates.kt
> +    EQ_LIST("", { lhs, rhs -> lhs.isEqualTo(rhs) }, list = true),
Yes this approach looks good, I will make the changes according to this. And I think subsequent changes will be required in `cypher-dsl` library also for these new fields, so I will check that also parallelly. Thank you.

2023-01-19 18:44 UTC, Andy2003 commented on core/src/main/kotlin/org/neo4j/graphql/Predicates.kt
> +    EQ_LIST("", { lhs, rhs -> lhs.isEqualTo(rhs) }, list = true),
There is no need to update `cypher-dsl` for this,  you can just use the predicates directly, like:

```kotlin
INCLUDES_ALL("_includes_all", { lhs, rhs ->
    val x: SymbolicName = org.neo4j.cypherdsl.core.Cypher.name("x")
    Predicates.all(x).`in`(lhs).where(x.`in`(rhs))
}, list = true),
```

2023-01-23 12:32 UTC, AakashSorathiya commented
Following new definitions are added

- test: [String!]
- test_NOT: [String!]
- test_INCLUDES_ALL: [String!]
- test_INCLUDES_NONE: [String!]
- test_INCLUDES_SOME: [String!]
- test_INCLUDES_SINGLE: [String!]

Test cases added for schema augmentation and cypher generation

2023-01-25 09:53 UTC, Andy2003 approved these changes

2023-01-25 09:56 UTC, merged